# yamllint disable-line rule:document-start

# -----------------------------------------------------
# CI pipeline to Build and Deploy MKDocs
# -----------------------------------------------------
  
name: 'Docs'
on:
    workflow_dispatch:
    push:
    
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name : prepare
        run: sh ./prepare.sh
          
      - name: Mike Deploy
        run: |
            mike list
            mike deploy 1.0.0
            #   python ./scripts/render_english_only.py
            #   git fetch origin gh-pages --depth=1 # fix mike's CI update
            #   mike deploy ${{ env.ACTIONTEST }}  -p --rebase
            #  mike set-default ${{ env.ACTIONTEST }} -p --rebase
            #  mike list