# yamllint disable-line rule:document-start

# -----------------------------------------------------
# CI pipeline to Build and Deploy MKDocs
# -----------------------------------------------------
  
name: 'Docs'
on:
    workflow_dispatch:
    push:
    
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  Mike-Deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name : prepare
        run: sh ./prepare.sh
          
      - name: Git Config
        run: git config user.name VinayaSri22 && git config user.email gangavarapuvinayasri14@gmail.com

      - name: Mike Deploy
        run: |
            mike list
            mike deploy --push --update-aliases 0.1 latest